add hypertheme
anubra266/choc-ui pull request #74
Opened 2022-02-28 02:34 UTC by panbenson

uses hypertheme for theme customization

2022-02-28 23:09 UTC, anubra266 approved these changes

2022-02-28 23:13 UTC, anubra266 commented on theme/index.tsx
> +  const [brand, setBrand] = useState(presets("default"));
```suggestion
  const [brand, setBrand] = useState<string | Record<number, string>>(
    presets('default'),
  )
```

2022-02-28 23:23 UTC, anubra266 requested changes
Hi @panbenson thanks for picking this up.
Your changes are unable to deploy, because there's a type error.
<img width="1002" alt="CleanShot 2022-03-01 at 00 21 57@2x" src="https://user-images.githubusercontent.com/30869823/156075298-0ae2bba8-3e3f-4a20-bd18-f3e74f860206.png">

I'm guessing, we're setting brand to accepts either a string, or a JSON object. We have to specify the type for brand, explicitly. 
`useState<Type>()`

2022-03-01 04:01 UTC, panbenson commented
thanks @anubra266, it should be a JSON type which I made updates to reflect. I'm unable to view the vercel logs, is there some way to repro the errors locally?

2022-03-01 07:58 UTC, anubra266 commented
@panbenson you can pull the latest changes,and use `yarn lint`

2022-03-02 01:18 UTC, panbenson commented
@anubra266 is whats failing on the vercel deployment? `yarn lint` is passing locally for me

![Screen Shot 2022-03-01 at 8 15 29 PM](https://user-images.githubusercontent.com/15132025/156276072-4761756d-658b-4281-9a0e-d018171f6289.png)

2022-03-03 00:32 UTC, panbenson commented
@anubra266 are you able to add me to the vercel team/copy me the logs? not able to access them from the "Details" link

2022-03-03 00:33 UTC, anubra266 commented
@panbenson, the picture here is the error showing up in deployment: https://github.com/anubra266/choc-ui/pull/74#pullrequestreview-895699881

2022-03-03 03:08 UTC, anubra266 approved these changes

2022-03-03 03:09 UTC, merged

2022-03-03 03:09 UTC, anubra266 commented
@all-contributors please add @panbenson for code